/* Quantum realizations in the browser: exact evolution and the two closures of the language.
 *
 * The same calculations as fieldbridge/quantum/language.py, on the matrices that site_data.py exports:
 *   hamiltonian       H = sum_k c_k(A) M_k over the terms that are switched on
 *   eigh              Hermitian eigendecomposition (complex Jacobi rotations)
 *   evolve            psi(t) = V exp(-i E t) V^dagger psi(0)
 *   closureDimension  Chapter 11: the smallest span that contains the observable and is invariant under i[H, .]
 *   lieClosure        Chapter 24: the Lie algebra generated by H and the observable under -i[ , ]
 *   su2               the canonical form of a three-dimensional algebra: rate |Omega|, weight |n|, angle theta
 *   analyze           all of the above, and the term whose removal leaves su(2)
 * Tested against numpy and fieldbridge.quantum in tests/test_site_engines.py.
 */
(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.FieldBridgeUnitary = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';
  const MAX_DIM = 40, TOL = 1e-9;
  const F = {sqrt: Math.sqrt, exp: Math.exp, log: Math.log, sin: Math.sin, cos: Math.cos, tanh: Math.tanh, abs: Math.abs};

  function value(tree, env) {
    const [op, a, b] = tree;
    if (op === 'number') return a;
    if (op === 'name') { if (a === 'pi') return Math.PI; if (!(a in env)) throw new Error('undeclared ' + a); return env[a]; }
    if (op === 'neg') return -value(a, env);
    if (F[op]) return F[op](value(a, env));
    const x = value(a, env), y = value(b, env);
    if (op === 'add') return x + y; if (op === 'sub') return x - y; if (op === 'mul') return x * y;
    if (op === 'div') return x / y; if (op === 'pow') return Math.pow(x, y);
    throw new Error('unsupported operation ' + op);
  }

  // ---------------------------------------------------------------------------------------- complex matrices
  const zeros = n => ({n, re: new Float64Array(n * n), im: new Float64Array(n * n)});
  const fromJSON = m => ({n: m.n, re: Float64Array.from(m.re), im: Float64Array.from(m.im)});
  function identity(n) { const I = zeros(n); for (let i = 0; i < n; i++) I.re[i * n + i] = 1; return I; }
  function copy(A) { return {n: A.n, re: Float64Array.from(A.re), im: Float64Array.from(A.im)}; }
  function axpy(Y, a, X) { for (let k = 0; k < Y.re.length; k++) { Y.re[k] += a * X.re[k]; Y.im[k] += a * X.im[k]; } return Y; }
  function scale(A, a) { const B = copy(A); for (let k = 0; k < B.re.length; k++) { B.re[k] *= a; B.im[k] *= a; } return B; }
  function mul(A, B) {
    const n = A.n, C = zeros(n);
    for (let i = 0; i < n; i++) for (let k = 0; k < n; k++) {
      const ar = A.re[i * n + k], ai = A.im[i * n + k];
      if (ar === 0 && ai === 0) continue;
      for (let j = 0; j < n; j++) {
        const br = B.re[k * n + j], bi = B.im[k * n + j];
        C.re[i * n + j] += ar * br - ai * bi; C.im[i * n + j] += ar * bi + ai * br;
      }
    }
    return C;
  }
  /** -i [A, B], Hermitian for Hermitian A and B */
  function bracket(A, B) {
    const P = mul(A, B), Q = mul(B, A), n = A.n, C = zeros(n);
    for (let k = 0; k < n * n; k++) { const dr = P.re[k] - Q.re[k], di = P.im[k] - Q.im[k]; C.re[k] = di; C.im[k] = -dr; }
    return C;
  }
  /** Re Tr(A B): the inner product of Hermitian matrices */
  function inner(A, B) {
    const n = A.n; let s = 0;
    for (let i = 0; i < n; i++) for (let k = 0; k < n; k++) s += A.re[i * n + k] * B.re[k * n + i] - A.im[i * n + k] * B.im[k * n + i];
    return s;
  }
  /** Tr(A^dagger B) as a complex number: the inner product of the observable closure */
  function vdot(A, B) {
    let r = 0, i = 0;
    for (let k = 0; k < A.re.length; k++) { r += A.re[k] * B.re[k] + A.im[k] * B.im[k]; i += A.re[k] * B.im[k] - A.im[k] * B.re[k]; }
    return [r, i];
  }
  const norm = A => { let s = 0; for (let k = 0; k < A.re.length; k++) s += A.re[k] * A.re[k] + A.im[k] * A.im[k]; return Math.sqrt(s); };
  function traceless(A) {
    const n = A.n, B = copy(A); let tr = 0, ti = 0;
    for (let i = 0; i < n; i++) { tr += A.re[i * n + i]; ti += A.im[i * n + i]; }
    for (let i = 0; i < n; i++) { B.re[i * n + i] -= tr / n; B.im[i * n + i] -= ti / n; }
    return B;
  }

  // ---------------------------------------------------------------------------------------- realization
  function hamiltonian(engine, params, active) {
    const n = engine.dim, H = zeros(n), env = {...(engine.fixed || {}), ...params};
    engine.terms.forEach((t, k) => {
      if (active && !active[k]) return;
      const c = value(t.tree, env);
      if (c !== 0) axpy(H, c, t._m || (t._m = fromJSON(t.matrix)));
    });
    return H;
  }
  const observable = engine => engine.observable._m || (engine.observable._m = fromJSON(engine.observable.matrix));

  // ---------------------------------------------------------------------------------------- eigenproblem
  /** Hermitian eigendecomposition by cyclic complex Jacobi rotations. Eigenvalues ascending; vectors in columns. */
  function eigh(H) {
    const n = H.n, A = copy(H), V = identity(n);
    const off = () => { let s = 0; for (let p = 0; p < n; p++) for (let q = p + 1; q < n; q++) s += A.re[p * n + q] ** 2 + A.im[p * n + q] ** 2; return s; };
    let scale2 = 0; for (let k = 0; k < n * n; k++) scale2 += A.re[k] ** 2 + A.im[k] ** 2;
    for (let sweep = 0; sweep < 100 && off() > 1e-30 * Math.max(scale2, 1e-300); sweep++) {
      for (let p = 0; p < n - 1; p++) for (let q = p + 1; q < n; q++) {
        const xr = A.re[p * n + q], xi = A.im[p * n + q], r = Math.hypot(xr, xi);
        if (r < 1e-300) continue;
        const er = xr / r, ei = xi / r;                  // e^{i phi}
        const tau = (A.re[q * n + q] - A.re[p * n + p]) / (2 * r);
        const t = (tau >= 0 ? 1 : -1) / (Math.abs(tau) + Math.sqrt(1 + tau * tau));
        const c = 1 / Math.sqrt(1 + t * t), s = t * c;
        // U on (p, q): [[c, s], [-s e^{-i phi}, c e^{-i phi}]]
        const upp = [c, 0], upq = [s, 0], uqp = [-s * er, s * ei], uqq = [c * er, -c * ei];
        for (let k = 0; k < n; k++) {                   // columns: A <- A U, V <- V U
          for (const M of [A, V]) {
            const ar = M.re[k * n + p], ai = M.im[k * n + p], br = M.re[k * n + q], bi = M.im[k * n + q];
            M.re[k * n + p] = ar * upp[0] - ai * upp[1] + br * uqp[0] - bi * uqp[1];
            M.im[k * n + p] = ar * upp[1] + ai * upp[0] + br * uqp[1] + bi * uqp[0];
            M.re[k * n + q] = ar * upq[0] - ai * upq[1] + br * uqq[0] - bi * uqq[1];
            M.im[k * n + q] = ar * upq[1] + ai * upq[0] + br * uqq[1] + bi * uqq[0];
          }
        }
        for (let k = 0; k < n; k++) {                   // rows: A <- U^dagger A
          const ar = A.re[p * n + k], ai = A.im[p * n + k], br = A.re[q * n + k], bi = A.im[q * n + k];
          A.re[p * n + k] = upp[0] * ar + upp[1] * ai + uqp[0] * br + uqp[1] * bi;
          A.im[p * n + k] = upp[0] * ai - upp[1] * ar + uqp[0] * bi - uqp[1] * br;
          A.re[q * n + k] = upq[0] * ar + upq[1] * ai + uqq[0] * br + uqq[1] * bi;
          A.im[q * n + k] = upq[0] * ai - upq[1] * ar + uqq[0] * bi - uqq[1] * br;
        }
        A.re[p * n + q] = A.im[p * n + q] = A.re[q * n + p] = A.im[q * n + p] = 0;
      }
    }
    const order = Array.from({length: n}, (_, i) => i).sort((i, j) => A.re[i * n + i] - A.re[j * n + j]);
    const values = Float64Array.from(order, i => A.re[i * n + i]), vectors = zeros(n);
    order.forEach((src, dst) => { for (let k = 0; k < n; k++) { vectors.re[k * n + dst] = V.re[k * n + src]; vectors.im[k * n + dst] = V.im[k * n + src]; } });
    return {values, vectors};
  }
  const column = (V, j) => ({re: Float64Array.from({length: V.n}, (_, k) => V.re[k * V.n + j]), im: Float64Array.from({length: V.n}, (_, k) => V.im[k * V.n + j])});
  /** top eigenvector of a Hermitian matrix (the preparation of the protocol P) */
  function topEigenstate(O) { const e = eigh(O); return column(e.vectors, O.n - 1); }
  function expect(M, psi) {
    const n = M.n; let s = 0;
    for (let i = 0; i < n; i++) {
      let r = 0, im = 0;
      for (let k = 0; k < n; k++) { const mr = M.re[i * n + k], mi = M.im[i * n + k]; r += mr * psi.re[k] - mi * psi.im[k]; im += mr * psi.im[k] + mi * psi.re[k]; }
      s += psi.re[i] * r + psi.im[i] * im;
    }
    return s;
  }
  /** psi(t) for a Hamiltonian: returns a function of t (the eigendecomposition is computed once) */
  function evolver(H, psi0) {
    const {values, vectors: V} = eigh(H), n = H.n;
    const cr = new Float64Array(n), ci = new Float64Array(n);
    for (let j = 0; j < n; j++) for (let k = 0; k < n; k++) {   // c = V^dagger psi0
      const vr = V.re[k * n + j], vi = V.im[k * n + j];
      cr[j] += vr * psi0.re[k] + vi * psi0.im[k]; ci[j] += vr * psi0.im[k] - vi * psi0.re[k];
    }
    return t => {
      const re = new Float64Array(n), im = new Float64Array(n);
      for (let j = 0; j < n; j++) {
        const ph = -values[j] * t, a = Math.cos(ph), b = Math.sin(ph), xr = cr[j] * a - ci[j] * b, xi = cr[j] * b + ci[j] * a;
        for (let k = 0; k < n; k++) { const vr = V.re[k * n + j], vi = V.im[k * n + j]; re[k] += vr * xr - vi * xi; im[k] += vr * xi + vi * xr; }
      }
      return {re, im};
    };
  }

  // ---------------------------------------------------------------------------------------- closures
  function closureBasis(H, O, maxDim = 256) {
    const basis = [];
    const add = A => {
      let v = copy(A);
      for (let pass = 0; pass < 2; pass++) for (const B of basis) { const [r, i] = vdot(B, v); for (let k = 0; k < v.re.length; k++) { v.re[k] -= r * B.re[k] - i * B.im[k]; v.im[k] -= r * B.im[k] + i * B.re[k]; } }
      const nv = norm(v);
      if (nv > TOL * Math.max(1, norm(A))) basis.push(scale(v, 1 / nv));
    };
    add(O);
    for (let i = 0; i < basis.length && basis.length <= maxDim; i++) add(scale(bracket(H, basis[i]), -1));   // i[H, A] = -(-i[H, A])
    return basis;
  }
  const closureDimension = (H, O, maxDim = 256) => closureBasis(H, O, maxDim).length;
  /** The frequencies with which the observable can move (site_data.observable_frequencies): i[H, .] on the closure
   *  of O is antisymmetric, with eigenvalues 0 and pairs +-i omega. One frequency: a rotating three-vector. */
  function closureFrequencies(H, O) {
    const basis = closureBasis(H, O), d = basis.length;
    if (d < 2) return [];
    const G = zeros(d);                                   // G = i M, M_jk = <B_j, i[H, B_k]>: Hermitian
    for (let k = 0; k < d; k++) {
      const LB = scale(bracket(H, basis[k]), -1);
      for (let j = 0; j < d; j++) { const [r, i] = vdot(basis[j], LB); G.re[j * d + k] = -i; G.im[j * d + k] = r; }
    }
    const w = Array.from(eigh(G).values), top = Math.max(1, ...w.map(Math.abs)), out = [];
    for (const v of w.filter(x => x > 1e-7 * top).sort((a, b) => a - b)) if (!out.length || v - out[out.length - 1] > 1e-7 * top) out.push(v);
    return out;
  }
  function lieClosure(gens, maxDim = MAX_DIM) {
    const basis = [];
    const add = M => {
      let v = copy(M);
      for (let pass = 0; pass < 2; pass++) for (const B of basis) axpy(v, -inner(B, v), B);
      const nv = Math.sqrt(Math.max(inner(v, v), 0));
      if (nv > TOL * Math.max(1, Math.sqrt(Math.max(inner(M, M), 0)))) {
        const w = zeros(v.n), n = v.n;   // Hermitian part, normalized
        for (let i = 0; i < n; i++) for (let k = 0; k < n; k++) {
          w.re[i * n + k] = (v.re[i * n + k] + v.re[k * n + i]) / (2 * nv); w.im[i * n + k] = (v.im[i * n + k] - v.im[k * n + i]) / (2 * nv);
        }
        basis.push(w);
      }
    };
    gens.forEach(g => add(traceless(g)));
    for (let i = 0; i < basis.length; i++) {
      for (let j = 0; j < i; j++) { add(bracket(basis[i], basis[j])); if (basis.length > maxDim) return {basis, closed: false}; }
    }
    return {basis, closed: true};
  }

  // ---------------------------------------------------------------------------------------- su(2)
  function symEig3(K) {   // real symmetric Jacobi for small matrices; returns {w, U} with U columns
    const n = K.length, A = K.map(r => r.slice()), U = Array.from({length: n}, (_, i) => Array.from({length: n}, (_, j) => +(i === j)));
    for (let sweep = 0; sweep < 60; sweep++) {
      let off = 0; for (let p = 0; p < n; p++) for (let q = p + 1; q < n; q++) off += A[p][q] ** 2;
      if (off < 1e-28) break;
      for (let p = 0; p < n - 1; p++) for (let q = p + 1; q < n; q++) {
        if (Math.abs(A[p][q]) < 1e-300) continue;
        const tau = (A[q][q] - A[p][p]) / (2 * A[p][q]), t = (tau >= 0 ? 1 : -1) / (Math.abs(tau) + Math.sqrt(1 + tau * tau));
        const c = 1 / Math.sqrt(1 + t * t), s = t * c;
        for (let k = 0; k < n; k++) { const a = A[k][p], b = A[k][q]; A[k][p] = c * a - s * b; A[k][q] = s * a + c * b; }
        for (let k = 0; k < n; k++) { const a = A[p][k], b = A[q][k]; A[p][k] = c * a - s * b; A[q][k] = s * a + c * b; }
        for (let k = 0; k < n; k++) { const a = U[k][p], b = U[k][q]; U[k][p] = c * a - s * b; U[k][q] = s * a + c * b; }
      }
    }
    return {w: A.map((r, i) => r[i]), U};
  }
  function inv3(M) {
    const [a, b, c] = M[0], [d, e, f] = M[1], [g, h, i] = M[2];
    const A = e * i - f * h, B = -(d * i - f * g), C = d * h - e * g, det = a * A + b * B + c * C;
    return [[A / det, -(b * i - c * h) / det, (b * f - c * e) / det], [B / det, (a * i - c * g) / det, -(a * f - c * d) / det], [C / det, -(a * h - b * g) / det, (a * e - b * d) / det]];
  }
  /** K of language.canonical_su2: rate, weight and angle, or null if the algebra is not su(2) */
  function su2(basis, H0, O0) {
    if (basis.length !== 3) return null;
    const f = [0, 1, 2].map(a => [0, 1, 2].map(b => { const C = bracket(basis[a], basis[b]); return [0, 1, 2].map(c => inner(C, basis[c])); }));
    const K = [0, 1, 2].map(a => [0, 1, 2].map(b => { let s = 0; for (let c = 0; c < 3; c++) for (let d = 0; d < 3; d++) s += f[a][d][c] * f[b][c][d]; return s; }));
    const {w, U} = symEig3(K), wmax = Math.max(1, ...w.map(Math.abs));
    if (!w.every(x => x < -1e-9 * wmax)) return null;
    const M = [0, 1, 2].map(i => [0, 1, 2].map(j => { let s = 0; for (let k = 0; k < 3; k++) s += U[i][k] * Math.sqrt(-w[k] / 2) * U[j][k]; return s; }));
    const Mi = inv3(M);
    let J = [0, 1, 2].map(a => { const X = zeros(H0.n); for (let b = 0; b < 3; b++) axpy(X, Mi[a][b], basis[b]); return X; });
    if (inner(bracket(J[0], J[1]), J[2]) < 0) J = J.map(X => scale(X, -1));
    const nrm = J.map(X => inner(X, X));
    const Om = J.map((X, a) => inner(H0, X) / nrm[a]), nv = J.map((X, a) => inner(O0, X) / nrm[a]);
    const W = Math.hypot(...Om), N = Math.hypot(...nv);
    if (W < 1e-12 || N < 1e-12) return null;
    const cos = Math.max(-1, Math.min(1, (nv[0] * Om[0] + nv[1] * Om[1] + nv[2] * Om[2]) / (N * W)));
    return {rate: W, weight: N, theta: Math.acos(cos), J};
  }

  /** The mechanism of a realization at parameters A with the terms that are switched on. */
  function analyze(engine, params, active) {
    const on = active || engine.terms.map(() => true);
    const H = hamiltonian(engine, params, on), O = observable(engine);
    const closure = closureDimension(H, O);
    const lie = lieClosure([H, O]);
    const canon = lie.closed ? su2(lie.basis, traceless(H), traceless(O)) : null;
    const out = {closure, dim: lie.closed ? lie.basis.length : '> ' + MAX_DIM, closed: lie.closed, reached: !!canon,
                 frequencies: closureFrequencies(H, O)};
    if (canon) Object.assign(out, {rate: canon.rate, theta: canon.theta * 180 / Math.PI, weight: canon.weight});
    else if (lie.closed && lie.basis.length > 3 && on.filter(Boolean).length > 1) {
      const found = [];
      on.forEach((isOn, k) => {
        if (!isOn) return;
        const rest = on.map((x, i) => x && i !== k), Hr = hamiltonian(engine, params, rest), L = lieClosure([Hr, O]);
        if (L.closed && su2(L.basis, traceless(Hr), traceless(O))) found.push(k);
      });
      if (found.length === 1) out.cause = found[0];
    }
    out.klass = canon ? 'rotation' : closure === 1 ? 'conserved' : 'obstructed';
    return out;
  }

  /** The measured signal, normalized by the top value of the observable: f(0) = 1 for the top eigenstate. */
  function signal(engine, params, active, psi0, times) {
    const H = hamiltonian(engine, params, active), O = observable(engine), ev = eigh(O).values;
    let o0 = 0; for (let i = 0; i < O.n; i++) o0 += O.re[i * O.n + i]; o0 /= O.n;
    const span = ev[ev.length - 1] - o0 || 1, psi = evolver(H, psi0);
    const frame = engine.frame ? (engine._frame || (engine._frame = engine.frame.map(fromJSON))) : null;
    return times.map(t => {
      const p = psi(t), row = {t, f: (expect(O, p) - o0) / span};
      if (frame) row.m = frame.map(Fa => expect(Fa, p) / (engine.j_top || 1));
      return row;
    });
  }
  const rabi = (theta, rate) => t => { const c = Math.cos(theta * Math.PI / 180), s = Math.sin(theta * Math.PI / 180); return c * c + s * s * Math.cos(rate * t); };

  return {value, zeros, fromJSON, mul, bracket, inner, traceless, hamiltonian, observable, eigh, topEigenstate, expect,
          evolver, closureDimension, closureFrequencies, lieClosure, su2, analyze, signal, rabi, MAX_DIM};
});
